In [1]:
import numpy as np
from rasutil import stateStrings

a=[[30,40,20,40],[40,30,10,20]]
arr=np.array(a)
print(arr)
print(arr.shape) #rows , columns
print(len(arr)) #number of nested value
print(np.size(arr)) #number of element
print(type(arr)) #datatype of variable
print(arr.dtype) #datatype of array
print(arr.astype(str)) #conversion of datatype


[[30 40 20 40]
 [40 30 10 20]]
(2, 4)
2
8
<class 'numpy.ndarray'>
int64
[['30' '40' '20' '40']
 ['40' '30' '10' '20']]


In [2]:
# #mathamatical operation and function in array
arr1=np.array([[30,40,20,40],[40,30,10,20]])
arr2=np.array([[40,30,10,20],[30,40,10,20]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(np.add(arr1,arr2))

[[70 70 30 60]
 [70 70 20 40]]
[[-10  10  10  20]
 [ 10 -10   0   0]]
[[1200 1200  200  800]
 [1200 1200  100  400]]
[[0.75       1.33333333 2.         2.        ]
 [1.33333333 0.75       1.         1.        ]]
[[70 70 30 60]
 [70 70 20 40]]


In [3]:
arr1=np.array([3,5,8,9])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 9 25 64 81]


In [4]:
arr1=np.array([9,25,64,81])
print(np.sqrt(arr1))

[3. 5. 8. 9.]


In [5]:
arr1=np.array([9,25,64,81])
print(np.square(arr1))

[  81  625 4096 6561]


In [6]:
#combining and splitting array
arr1=np.array([[9,25],[64,81]])
arr2=np.array([[9,5],[4,8]])
print(np.concatenate([arr1,arr2]))

[[ 9 25]
 [64 81]
 [ 9  5]
 [ 4  8]]


In [7]:
print(np.concatenate([arr1,arr2],axis=1))

[[ 9 25  9  5]
 [64 81  4  8]]


In [8]:
print(np.concatenate([arr1,arr2],axis=0))

[[ 9 25]
 [64 81]
 [ 9  5]
 [ 4  8]]


In [9]:
print(np.hstack([arr1,arr2])) #horizontal concatenation

[[ 9 25  9  5]
 [64 81  4  8]]


In [10]:
print(np.vstack([arr1,arr2])) #vertical concatenation

[[ 9 25]
 [64 81]
 [ 9  5]
 [ 4  8]]


In [11]:
#splitte
a=np.array([1,2,3,4,5,6,7,8])
print(np.array_split(a,2))
print(np.array_split(a,3))
print(np.array_split(a,4))

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [12]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array_split(a,2)
print(b[1])

[5 6 7 8]


In [13]:
#adding and removing element in array
a=np.array([30,40,20,40])
print(np.append(a,[90,100])) #append values

[ 30  40  20  40  90 100]


In [14]:
print(np.insert(a,0,100)) #insert values
print(np.insert(a,1,100)) # array index value
print(np.insert(a,2,100))

[100  30  40  20  40]
[ 30 100  40  20  40]
[ 30  40 100  20  40]


In [15]:
print(np.insert(a,3,[100,50],axis=0))

[ 30  40  20 100  50  40]


In [16]:
a=np.array([[20,40],[50,60]])
print(np.insert(a,[1,2],[50],axis=0))

[[20 40]
 [50 50]
 [50 60]
 [50 50]]


In [17]:
print(a)
print(np.delete(a,1,axis=0))

[[20 40]
 [50 60]]
[[20 40]]


In [18]:
#Numpy - sort, filter and
#sort
import numpy as np
ar=np.array([[30,40,20,40],[40,30,10,20]])
print(np.sort(ar))

[[20 30 40 40]
 [10 20 30 40]]


In [19]:
ar=np.array([3,7,5,4,9,0,2])
s=np.where(ar==4)
s=np.where(ar<4)
s=np.where(ar%2==0)
ss=np.searchsorted(ar,3)
print(s)

(array([3, 5, 6]),)


In [20]:
ss=np.searchsorted(ar,5)
print(ss)

7


In [21]:
ar=np.array([30,40,20,40])
fa=[True,False,True,False]
new=ar[fa]
print(new)

[30 20]


In [22]:
ar=np.array([2,3,4,5])
fa=ar%2==0
ar=ar>3
new=ar[fa]
print(new)

[False  True]


In [23]:
#Aggregating function in array
import numpy as np
a=np.array([10,20,30,60,50,90,40])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.median(a))
print(np.std(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

300
10
90
40.0
24.907993963089563
7
42.857142857142854
[ 10  30  60 120 170 260 300]
[         10         200        6000      360000    18000000  1620000000
 64800000000]


In [24]:
a=[100,150,200,190,250,130]
b=[10,50,30,40,60,70]
price=np.array(a)
quantity=np.array(b)
print(price,"\n", quantity)
print()
print(np.cumprod([price,quantity],axis=0))


[100 150 200 190 250 130] 
 [10 50 30 40 60 70]

[[  100   150   200   190   250   130]
 [ 1000  7500  6000  7600 15000  9100]]


In [25]:
a=[10,50,30,40,60,70]
b=[10,50,30,40,60,70]
price=np.array(a)
quantity=np.array(b)
print(price,"\n", quantity)
print()
c=np.cumprod([price,quantity],axis=0)
print(c[1].sum())

[10 50 30 40 60 70] 
 [10 50 30 40 60 70]

13600


In [ ]:
import numpy as np
baked_food=[100,200,150,250,300,350,199]
baked_food=np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(np.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

In [28]:
# -1 represent inversely proportional relationship
# 1 represents proportional relation
# 0 means no relation
import numpy as np
tobacco_consumption =[10,50,30,40,60,70]
death =[100,150,200,70,50,120]
print(np.corrcoef(tobacco_consumption,death))

[[ 1.         -0.20317593]
 [-0.20317593  1.        ]]


In [29]:
import numpy as np
price =[200,100,250,150,300]
sales =[10,20,7,17,4]

print(np.corrcoef(price,sales))

[[ 1.         -0.98666607]
 [-0.98666607  1.        ]]




#Pandas



In [30]:
import pandas as pd
data={"name":["john","peter","lisa"],
      "age":[25,28,31],
      "salary":[2000,2000,2000]}
df = pd.DataFrame(data)
print(df)


    name  age  salary
0   john   25    2000
1  peter   28    2000
2   lisa   31    2000


In [ ]:
# # for import csv file from any folder
data=pd.read_csv("C:/Users/Nitisha sharma/Documents/one drive/OneDrive/Desktop/python data analytics full_employee_data.csv")

print(data)

In [ ]:
#for Excel file
import pandas as pd
data=pd.read_excel("full_employee_data.excel.xlsx")
print(data)

In [ ]:
import pandas as pd
data=pd.read_excel("Employee-Management-Sample-Data.xlsx")
print(data)

In [ ]:
import pandas as pd
data = pd.read_excel("Employee-Management-Sample-Data.xlsx")
print(data.head(20))
print(data.tail(20))

In [ ]:
print(data.info)

In [ ]:
print(data.describe())

In [ ]:
print(data.isnull().sum())

In [ ]:
# #handling duplicate values
import pandas as pd
data=pd.read_excel("unclean_employee_data.xlsx")
print(data)

In [ ]:
print(data["EmployeeID"].duplicated().sum())

In [ ]:
print(data.drop_duplicates("EmployeeID"))

In [ ]:
# Handling Null values or missing value
import pandas as pd
data = pd.read_csv("unclean_employee_data.csv")
print(data.head(10))

In [ ]:
print(data.isnull().sum())

In [ ]:
print(data.dropna())

In [ ]:
print(data)

In [ ]:
import pandas as pd
data = pd.read_csv("unclean_employee_data.csv")
print(data.dropna(subset=["EmployeeID"]))

In [ ]:
print(data)

In [ ]:
import numpy as np
print(data.replace(np.nan,"hii"))

In [ ]:
data["Salary"]=data["Salary"].replace(np.nan,"50000.0")
print(data)

In [ ]:
data["Department"]=data["Department"].replace(np.nan,"Human Resources")
print(data)

In [ ]:
import pandas as pd
data=pd.read_csv("unclean_employee_data.csv")
print(data)

In [ ]:
print(data)

In [ ]:
print(data["salary"].mean())

In [ ]:
print(data.fillna(method="ffill"))

In [ ]:
import pandas as pd
data=pd.read_csv("unclean_employee_data.csv")
print(data.fillna(method="bfill"))

In [ ]:
print(data.fillna(method="ffill"))

In [ ]:
print(data.fillna("hello"))

# column transformation in pandas part 1

In [ ]:
import pandas as pd
data = pd.read_excel("unclean_employee_data.xlsx")

df.loc[(df["bonus %"]==0), "GetBonus"]= "no bonus"
df.loc[(df["bonus %"]>0), "GetBonus"]= "bonus"
print(data.head(10))


In [ ]:
data = pd.read_excel("unclean_employee_data.xlsx")
print(data.head(10))
data["Full Name"]=data["First name "].str.capitalize()+" "+ data["Last name"].str.capitalize()
print(data.head(10))

# part 2

In [ ]:
import pandas as pd
data = pd.read_excel("unclean_employee_data.xlsx")
print(data.head(10))
data["Bonus"]=(data["Salary"]/100)*20
print(data.head(10))

In [42]:
data = {"Months":["January","February","March","April"]}

a=pd.DataFrame(data)
print(a)

def extract(value):
    return value[0:3]

a["Short_months"]=a["Months"].map(extract)
print(a)

     Months
0   January
1  February
2     March
3     April
     Months Short_months
0   January          Jan
1  February          Feb
2     March          Mar
3     April          Apr



Group by pandas


In [ ]:
import pandas as pd
data = pd.read_excel("unclean_employee_data.xlsx")
print(data.head(10))

In [ ]:
gp=data.groupby(["Department","Name"]).agg({"EmployeeID":"count"})
print(gp.head(20))
#print(data.head(10))

In [ ]:
gp1=data.groupby("Location").agg({"Salary":"max","PerformanceRating":"min"})
print(gp1.head(20))

In [ ]:
gp2=data.groupby("EmployeeID").agg({"Name":"sum"})
print(gp2.head(20))


#Merge, join and concatenate in pandas


In [44]:
import pandas as pd
data1={"EmployeeID":["E01","E02","E03","E04"],
       "Names":["Ram","shyam","Rima","sima"]}
data2={"EmployeeID":["E01","E05","E03","E06"],
       "Salary":[100,200,300,400]}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
print(df1)
print()
print(df2)


  EmployeeID  Names
0        E01    Ram
1        E02  shyam
2        E03   Rima
3        E04   sima

  EmployeeID  Salary
0        E01     100
1        E05     200
2        E03     300
3        E06     400


In [45]:
print(pd.merge(df1,df2,on="EmployeeID"))

  EmployeeID Names  Salary
0        E01   Ram     100
1        E03  Rima     300


In [46]:
print(pd.merge(left=df2,right=df1,on="EmployeeID",how="left"))

  EmployeeID  Salary Names
0        E01     100   Ram
1        E05     200   NaN
2        E03     300  Rima
3        E06     400   NaN


In [47]:
print(pd.merge(left=df1,right=df2,on="EmployeeID",how="right"))

  EmployeeID Names  Salary
0        E01   Ram     100
1        E05   NaN     200
2        E03  Rima     300
3        E06   NaN     400


In [48]:
import pandas as pd
data1={"EmployeeID":["E01","E02","E03","E04"],
       "Names":["Ram","shyam","Rima","sima"],
       "age":[10,20,30,40]}
data2={"EmployeeID":["E05","E06","E07","E08"],
       "Names":["John","Don","Kon","Lon"],
       "age":[21,24,35,44]}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

In [49]:
print(pd.concat([df1,df2],ignore_index=True))

  EmployeeID  Names  age
0        E01    Ram   10
1        E02  shyam   20
2        E03   Rima   30
3        E04   sima   40
4        E05   John   21
5        E06    Don   24
6        E07    Kon   35
7        E08    Lon   44



#compare dataframes


In [50]:
import pandas as pd
dictionary = {"fruits":["mango","apple","banana","papaya"],
              "price":[100,200,150,50],
              "quantity":[15,10,30,33]}
df1=pd.DataFrame(dictionary)
print(df1)

df2=df1.copy()

df2.loc[0,"price"]=120
df2.loc[1,"price"]=220
df2.loc[2,"price"]=400
df2.loc[0,"quantity"]=20
df2.loc[1,"quantity"]=15
df2.loc[2,"quantity"]=35

print(df2)
print(df1.compare(df2,align_axis=0))
print(df1.compare(df2,keep_shape=True))

   fruits  price  quantity
0   mango    100        15
1   apple    200        10
2  banana    150        30
3  papaya     50        33
   fruits  price  quantity
0   mango    120        20
1   apple    220        15
2  banana    400        35
3  papaya     50        33
         price  quantity
0 self   100.0      15.0
  other  120.0      20.0
1 self   200.0      10.0
  other  220.0      15.0
2 self   150.0      30.0
  other  400.0      35.0
  fruits        price        quantity      
    self other   self  other     self other
0    NaN   NaN  100.0  120.0     15.0  20.0
1    NaN   NaN  200.0  220.0     10.0  15.0
2    NaN   NaN  150.0  400.0     30.0  35.0
3    NaN   NaN    NaN    NaN      NaN   NaN



#Pivoting and Melting DataFrames - Pandas


In [51]:
import pandas as pd
dictionary = {"Keys":["K1","K2","K1","K2"],
              "Names":["john","Ben","David","Peter"],
              "Houses":["Green","blue","red","yellow"],
              "Grades":["3rd","4th","5th","6th"]}
df=pd.DataFrame(dictionary)
print(df)
print(df.pivot(index="Keys",columns="Names",values=["Houses","Grades"]))

  Keys  Names  Houses Grades
0   K1   john   Green    3rd
1   K2    Ben    blue    4th
2   K1  David     red    5th
3   K2  Peter  yellow    6th
      Houses                      Grades                 
Names    Ben David   Peter   john    Ben David Peter john
Keys                                                     
K1       NaN   red     NaN  Green    NaN   5th   NaN  3rd
K2      blue   NaN  yellow    NaN    4th   NaN   6th  NaN


In [52]:
import pandas as pd

dictionary = {"Names": ["john", "Ben", "David", "Peter"],
              "Houses": ["Green", "blue", "red", "yellow"],
              "Grades": ["3rd", "4th", "5th", "6th"]}
df = pd.DataFrame(dictionary)
print(df)
print(pd.melt(df, id_vars=["Names"],value_vars=["Houses","Grades"],var_name="Houses&Grades",value_name="value"))
# print(df.pivot(index="Keys", columns="Names", values=["Houses", "Grades"]))

   Names  Houses Grades
0   john   Green    3rd
1    Ben    blue    4th
2  David     red    5th
3  Peter  yellow    6th
   Names Houses&Grades   value
0   john        Houses   Green
1    Ben        Houses    blue
2  David        Houses     red
3  Peter        Houses  yellow
4   john        Grades     3rd
5    Ben        Grades     4th
6  David        Grades     5th
7  Peter        Grades     6th
